// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vonemvvoyzdmzypppmuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvbmVtdnZveXpkbXp5cHBwbXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTc1MTMsImV4cCI6MjA2Njk3MzUxM30.cy8_clHAA2ojXqCWYFC6wBXJEty9wyOSCQOEvoJLYQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});